on:
    schedule:
      - cron: '0 1-23 * * *'
      - cron: '0 0 * * *'
jobs:
  test_schedule:
    name: Test schedule
    runs-on: ubuntu-latest
    steps:
      - name: Skip this step every 24 hours
        if: github.event_name == 'schedule' && github.event.schedule != '0 0 * * *'
        run: echo "This step will be skipped every 24 hours"