on:
    workflow_dispatch:
    schedule:
      - cron: '*/2 * * * *'
      - cron: '0 0 * * *'
jobs:
  test_schedule:
    name: Test schedule
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!!!"
